# Constants
CATEGORY_TITLE_MAX_LEN: int = 256
COMMENT_TEXT_MAX_LEN: int = 256
LOCATION_NAME_MAX_LEN: int = 256
MAX_ITEMS_ON_PAGE: int = 10
POST_LIST_NUM: int = 5
POST_TITLE_MAX_LEN: int = 256
USER_NAME_MAX_LEN: int = 20
