# Generated by Django 3.2.16 on 2024-02-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',), 'verbose_name': 'коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
